In [6]:
import pandas as pd
import geopandas as gpd

In [7]:
def choropleth(df, column, title, cmap = 'viridis', ax=None):
    """
    Function to plot a choropleth
    
    Output: Choropleth with a vertical color bar
    
    Input:
    ---
      df : The GeoDataFrame that holds the values to be plotted
      column : The column of the dataframe whose values are plotted
      title : Title of the plot
      cmap : color map used
    """
    f, ax = plt.subplots(figsize=(9,9))
    plt.title(title, size=20)
    ax = df.plot(column=column, colormap=cmap,alpha = 1, linewidth=0.3, scheme='fischer_jenks', axes=ax)
    vmin, vmax = min(df[column].values), \
                max(df[column].values)
    ax.axis('off')
    fig = ax.get_figure()
    cax = fig.add_axes([0.9, 0.1, 0.03, 0.8])
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=vmin, vmax=vmax))
    sm._A = []
    fig.colorbar(sm, cax=cax)

In [ ]:
title = "Business Density by Zipcodes, 2000"
choropleth(zipcodeDF, 'density_2000', title, 'Blues')

In [12]:
refugee_data = pd.read_csv('./Data/ref_country_of_Asylum/18f4ebc1-6751-4d6f-b1c5-28a830b148f9_Data.csv')
refugee_data.head()

,﻿Series Name,Series Code,Country Name,Country Code,1990 [YR1990],2000 [YR2000],2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016]
0,Refugee population by country or territory of ...,SM.POP.REFG,Afghanistan,AFG,50,..,42,37,37,6434,3009,16187,16863,300423,257554,..
1,Refugee population by country or territory of ...,SM.POP.REFG,Albania,ALB,..,523,77,65,70,76,82,86,93,104,104,..
2,Refugee population by country or territory of ...,SM.POP.REFG,Algeria,DZA,169110,169656,94137,94093,94137,94144,94148,94133,94150,94128,94182,..
3,Refugee population by country or territory of ...,SM.POP.REFG,American Samoa,ASM,..,..,..,..,..,..,..,..,..,..,..,..
4,Refugee population by country or territory of ...,SM.POP.REFG,Andorra,ADO,..,..,..,..,..,..,..,..,..,..,..,..